baseURL = "https://github.com/"
title = "Hossein Adib Profile"

# prevent build failures when using Hugo's Instagram shortcode due to deprecated
# Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

[Params]
# Note: This is for the meta description, which is different from the
# "description" displayed in the prompt.
description = "Hossein Adib's Portfolio!"
  [Params.Prompt]
  # Note: color scheme
  # Note: You can choose between
  # Note: hugo-theme-ghci original: ["Haskell"]
  # Note: hugo-theme-ghci built-in (inherited from hugo-theme-shell):
  #           ["prompt-powershell", "prompt-ubuntu", "prompt-retro", "prompt-white"]
  # Note: gogh theme: https://mayccoll.github.io/Gogh/
  scheme = "prompt-powershell"

  # Note: variables for GHCi heading
  # GHCi, version [ghcVersion]: [ghcURL]  :? for help
  ghcVersion = "9.0.2"
  ghcURL = "https://www.haskell.org/ghc/"

  # Note: speed at which text is displayed on the prompt
  # Note: if set to 0, typing animation will be disabled
  # Note:
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown or Org file
  headingDelay = 0 # GHCi heading speed : GHCi, version [ghcVersion]: [ghcURL]  :? for help
  promptDelay = 0 # prompt speed : ghci>, |
  stdoutDelay = 0 # stdout speed : [description] , files in Params.Tree
  codeDelay = 70 # code speed : myStringTransform :: String -> String

  # Note: speed at which text is displayed on the activity pages
  # Note: if set to 0, typing animation will be disabled
  # Note: 
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  titleDelay = 0 # title speed : "title" in front matter
  contentDelay = 0 # content speed : content in .md file

  # Note: variables that control timing with regards to dynamic scrolling as the
  # prompt is updated
  # Note: these variables should not need to be tuned most likely (in-place due
  # to poor dynamic scrolling implementation due to limitations of more ideal
  # functionality like scrollIntoView + dynamically rendered elements)
  #
  # Note: units are in milliseconds
  #
  # Note: a FIXME comment is in place for this functionality. Once fixed, these
  # variables will be deprecated.
  scrollDownUpdateInterval = 50 # Controls the interval duration between scroll to bottom calls
  scrollDownTimeoutAfterTypeEffect = 500 # Controls time after typing effect is done to cancel subsequent scroll down calls

  [Params.Package] 
  # Note: controls properties related to the Haskell "module" that contains
  # functions with information about the site and profile
  importPackage = "Site" # module name
  importQualified = false # whether module should be a qualified import

  [Params.Profile]
  # Note: in output
  # ghci> [sysInfoFcnName]
  # Login name: [userName]
  # Host name: [pcName]
  # ghci> [profileDescriptionFcnName]
  # [description]
  #
  userName = "HosseinAdib"
  pcName = "i2ib4sunshine"
  sysInfoFcnName = "getSystemInfo"
  profileDescriptionFcnName = "getProfileDescription"

  # Note: If you want to use a Markdown or Org file, you can use the following
  # description = "/description.md"
  # Note: and put the description.md in /content/description.md
  description = """
  Hi I am Hossein Adib!
  Nice to meet you!
  
  """

    [Params.Profile.Picture]
    use = true
    fcnName = "getProfilePicture"
    # Note: if githubUserName is non-empty, src is ignored
    githubUserName = "HosseinAdib-Hub"
    src = "https://avatars.githubusercontent.com/u/663815?v=4" # path/url to image

  [Params.Tree]
  use = true
  fcnName = "getActivity"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR CONTENT FILE"]
  files = [ 
    ["Delphi Programming Language", ""],
    [".Net2-.Net CORE5", ""],
	["ASP.NET", ""],
	["MVC", ""],
	["Entity Framework", ""],
	["Git", ""],
    ["MSSQL SERVERs", ""],
	["MySql", ""],
	["LiteSql", ""],
	
  ]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.85.0"
